angular
    .module('disruptApp')
    .controller('DisruptController', DisruptController);

    function DisruptController(){
        var self = this;
        self.foo = 'bar'
        self.innovation = "Build the next revolution"
        self.leftWords = [
            'Twitter',
            'Android',
            'Facebook',
            'Instagram',
            'Vine',
            'tumblr',
            'reddit',
            'YouTube',
            'Google',
            'Yahoo',
            'Amazon',
            'iOS',
            'Kickstarter',
            'Twitch',
            'Gmail',
            'Foursquare',
            'Yelp',
            'eBay',
            'okCupid',
            'Netflix',
            'Hulu',
            'Amazon Prime',
            'Social media',
            'Zazzle',
            'Etsy',
            'Crowdfunding',
            'Khan Academy',
            'iTunes',
            'Google Maps',
            'imgur',
            'The whole world',
            'A grocery list',
            'Itinerary planning',
            'A cooking guide',
            'A coding textbook',
            'Math instruction',
            'A new way to look at communication',
            'A revolutionary platform',
            'A bass fishing platform',
            'A revolution in veganism',
            'The next phase of green living',
            'The urban village',
            'Organic living',
            'Social networking',
            'Online dating',
            'Uber',
            'Skype',
            'Videochatting',
            'Fitbit',
            'Minecraft',
            'Angry Birds',
            'Candy Crush',
        ];
        self.rightWords = [
           'for pictures',
            'for pet owners',
            'for the tumblr generation',
            'for the new economy',
            'with motion control',
            'with 4k functionality',
            'with a mobile-facing UI',
            'like it\'s nbd',
            'on Android',
            'on steroids',
            'powered by iOS',
            'meets Instagram',
            'because YOLO',
            'focusing on the end user',
            'for your television',
            'for your tablet',
            'with social networking elements',
            'for college students',
            'in a flat world',
            'designed for China',
            'for Six Sigma companies',
            'from your living room',
            'in your car',
            'from anywhere in the world',
            'for telecommuters',
            'from your self-driving car',
            'for tablets',
            'for smartphones',
            'without the hassle',
            'in your underwear',
            'in your pajamas',
            'for professionals',
            'that brings the world together',
            'to make the world a better place',
            'that actually works',
            'that just works',
            'for teachers',
            'for lawyers',
            'for engineers',
            'for accountants',
            'for mechanics',
            'for retail',
            'for college admissions',
            'for professors',
            'for research',
            'that your grandma could use',
            'to build a better tomorrow',
            'that makes the whole world a local community',
            'that can go viral',
            'in a water bottle',
            'for EDM enthusiasts',
            'with an exclusivity element',
            'for foodies',
            'to show off your parkour skills',
        ];
        self.disrupt = function(){
            num1 = Math.floor(Math.random() * self.leftWords.length)
            num2 = Math.floor(Math.random() * self.rightWords.length)
            self.innovation = self.leftWords[num1] + ' ' + self.rightWords[num2]
        }
    }